module StimulusSpec
  VERSION: String

  def self.configuration: () -> Configuration
  def self.configure: () { (Configuration) -> void } -> void
  def self.reset_configuration!: () -> Configuration
  def self.install_rspec_integration: (untyped config) -> void

  class Configuration
    attr_accessor auto_include: bool

    def initialize: () -> void
  end

  module Matchers
    def have_stimulus_controller: (String name) -> HaveStimulusController
    def have_stimulus_action: (String descriptor) -> HaveStimulusAction
    def have_stimulus_target: (String controller, String target) -> HaveStimulusTarget
    def have_stimulus_value: (String controller, String name, ?String? expected) -> HaveStimulusValue
    def have_stimulus_class: (String controller, String name, ?String? expected) -> HaveStimulusClass
    def have_stimulus_outlet: (String controller, String outlet, ?String? selector) -> HaveStimulusOutlet

    class HaveStimulusController
      def initialize: (String name) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end

    class HaveStimulusAction
      def initialize: (String descriptor) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end

    class HaveStimulusTarget
      def initialize: (String controller, String target) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end

    class HaveStimulusValue
      def initialize: (String controller, String name, ?String? expected) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end

    class HaveStimulusClass
      def initialize: (String controller, String name, ?String? expected) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end

    class HaveStimulusOutlet
      def initialize: (String controller, String outlet, ?String? selector) -> void
      def matches?: (untyped subject) -> bool
      def does_not_match?: (untyped subject) -> bool
      def failure_message: () -> String
      def failure_message_when_negated: () -> String
      def description: () -> String
    end
  end

  module Capybara
    module Matchers
      def have_stimulus_controller: (String name) -> HaveStimulusController
      def have_stimulus_action: (String descriptor) -> HaveStimulusAction
      def have_stimulus_target: (String controller, String target) -> HaveStimulusTarget
      def have_stimulus_value: (String controller, String name, ?String? expected) -> HaveStimulusValue

      class HaveStimulusController
        def initialize: (String name) -> void
        def matches?: (untyped page) -> bool
        def does_not_match?: (untyped page) -> bool
        def failure_message: () -> String
        def failure_message_when_negated: () -> String
        def description: () -> String
      end

      class HaveStimulusAction
        def initialize: (String descriptor) -> void
        def matches?: (untyped page) -> bool
        def does_not_match?: (untyped page) -> bool
        def failure_message: () -> String
        def failure_message_when_negated: () -> String
        def description: () -> String
      end

      class HaveStimulusTarget
        def initialize: (String controller, String target) -> void
        def matches?: (untyped page) -> bool
        def does_not_match?: (untyped page) -> bool
        def failure_message: () -> String
        def failure_message_when_negated: () -> String
        def description: () -> String
      end

      class HaveStimulusValue
        def initialize: (String controller, String name, ?String? expected) -> void
        def matches?: (untyped page) -> bool
        def does_not_match?: (untyped page) -> bool
        def failure_message: () -> String
        def failure_message_when_negated: () -> String
        def description: () -> String
      end
    end
  end
end
